Added Vue commands #7
sliit-foss/cli-explorer pull request #48
Opened 2024-06-24 14:15 UTC by icy-r

Added basic VueJs CLI commands to the site. (#7 )

2024-08-01 15:13 UTC, SasinduNanayakkara approved these changes
LGTM

2024-08-01 15:14 UTC, SasinduNanayakkara approved these changes
LGTM

2024-08-03 13:19 UTC, ThulinaWickramasinghe commented
@icy-r Can you make the user navigate to a page containing this data when the Vue.js icon is clicked?

2024-08-03 14:37 UTC, ThulinaWickramasinghe requested changes

2024-08-03 14:37 UTC, ThulinaWickramasinghe commented on src/data/vue.js/tertiary-options.js
@icy-r  Shall we, remove this since there's no data?

2024-08-03 14:37 UTC, ThulinaWickramasinghe commented on src/data/vue.js/primary-options.js
> +});
I see we're duplicating this in every folder containing data. Shall we create a new folder called utils and move this to it and then import? Can you do this change for other folders which contain data as well?

@icy-r

2024-08-03 16:05 UTC, icy-r commented
Deleted unwanted files and codes as mentioned. #48

2024-08-03 16:37 UTC, icy-r commented
Shorter function added for code simplification. #48

2024-08-03 16:55 UTC, icy-r commented on src/data/vue.js/tertiary-options.js
sure

2024-08-03 17:10 UTC, ThulinaWickramasinghe requested changes

2024-08-03 17:10 UTC, ThulinaWickramasinghe commented on src/util/Shorter.js
When naming functions in js we normally use camel case. 

And can you rename this to a more meaningful name based on it's functionality? 

Also utils seems more meaningful and convenient than it's singular form util since we might add more utility functions later.

Also try to format the code before committing.

2024-08-03 17:10 UTC, ThulinaWickramasinghe commented on src/util/Shorter.js
> +  }
Add an empty line after this

2024-08-03 17:10 UTC, ThulinaWickramasinghe commented on src/util/Shorter.js
> +  }
Add an empty line after this

2024-08-03 17:10 UTC, ThulinaWickramasinghe commented on src/util/Shorter.js
> +if (x.value < y.value) {
Add space at start. Use prettier

2024-08-03 17:22 UTC, ThulinaWickramasinghe commented on src/util/Shorter.js
This function is comparing 2 values and helps to sort them alphabetically.

2024-08-03 18:39 UTC, icy-r commented
Thanks for the comments. I've fixed those errors. If there anything else i should consider refactoring please let me know... @ThulinaWickramasinghe

2024-08-04 05:49 UTC, ThulinaWickramasinghe commented
> Thanks for the comments. I've fixed those errors. If there anything else i should consider refactoring please let me know... @ThulinaWickramasinghe

Wonderful. Everything is perfect right now, but we need one small change. 

Can you also rename the file AlphabeticalSort.js to alphabetical-sort.js so that the we can make sure we're following the same file naming guideline everywhere? 

FYI, only when naming react components it's necessary to follow Pascal Case. Even the react components' file names can follow any other naming case(mostly pascal or kebab). We prefer kebab case, especially for functions.

2024-08-04 05:53 UTC, ThulinaWickramasinghe requested changes

2024-08-04 05:53 UTC, ThulinaWickramasinghe commented on src/data/next.js/primary-options.js
Remove empty line at the end

2024-08-04 05:53 UTC, ThulinaWickramasinghe commented on src/data/npm/index.js
> +
Remove empty line

2024-08-04 05:53 UTC, ThulinaWickramasinghe commented on src/utils/AlphabeticalSort.js
Rename file to alphabetical-sort.js

2024-08-04 11:23 UTC, icy-r commented
sure.. i just made those changes. thanks!

2024-08-10 13:46 UTC, ThulinaWickramasinghe approved these changes
LGTM. Thanks @icy-r

2024-08-10 13:46 UTC, merged