Added Yarn Commands
sliit-foss/cli-explorer pull request #52
Opened 2024-08-03 15:16 UTC by JanukshanS

Added Yarn CLI Commands #4

2024-08-03 15:33 UTC, ThulinaWickramasinghe requested changes

2024-08-03 15:33 UTC, ThulinaWickramasinghe commented on src/data/yarn/tertiary-options.js
Remove this since there aren't any tertiary options . @JanukshanS

2024-08-03 15:33 UTC, ThulinaWickramasinghe commented on src/data/yarn/primary-options.js
> +  });
Check this and coordinate with icy.

https://github.com/sliit-foss/cli-explorer/pull/48#discussion_r1702792098

2024-08-03 15:33 UTC, ThulinaWickramasinghe commented on src/data/yarn/index.js
> +export { tertiaryOptions as optionsThird } from './tertiary-options';
Remove from here as well.

2024-08-03 17:11 UTC, JanukshanS commented on src/data/yarn/tertiary-options.js
Ok Done

2024-08-10 15:07 UTC, JanukshanS commented
I have made the required changes can you check it? @ThulinaWickramasinghe

2024-08-12 18:12 UTC, ThulinaWickramasinghe approved these changes

2024-08-12 18:12 UTC, merged

2024-08-12 18:13 UTC, ThulinaWickramasinghe commented
> I have made the required changes can you check it? @ThulinaWickramasinghe

Seemed fine. Merged it.